import {Shell} from "../../components";

const projects={
 smartgate:{num:"01",type:"INTERNAL PRODUCT SIMULATION",title:"SMARTGATE",intro:"A visitor-management product exercise built around approvals, gate operations, notifications and auditability.",status:"Internal simulation / professional QA & engineering exercise",tags:["Node / Express / TypeScript","PostgreSQL","JWT / bcrypt","QA / API / SQL"],sections:[
  ["01 / Product","Operational workflow","SMARTGATE models a controlled visitor journey: request, verification, approval, gate entry, return and audit trail. The project is used to demonstrate product thinking and quality engineering — not presented as external client work."],
  ["02 / Architecture","Connected system","The solution is structured around a backend API, PostgreSQL data layer, authentication, validation and role-aware workflows. The UI and QA process sit on top of that shared system of record."],
  ["03 / Quality","Test the risk, not just the screen","QA scenarios cover positive and negative visitor flows, authentication, API behavior, database consistency, defect lifecycle and release readiness. Manual and automation paths can reinforce each other."],
  ["04 / Release","From build to UAT","Development moves through a controlled QA environment, defect reporting, fixes, retesting and UAT before a release decision. The point is repeatability and traceability."],
 ],flow:["Request","Verify","Approve","Check-in","Return","Audit"]},
 "enterprise-operations":{num:"02",type:"REPRESENTATIVE CAPABILITY",title:"Enterprise Operations Platform",intro:"A representative internal platform concept connecting people, projects, tasks, records and management reporting.",status:"Representative capability — not a client case study",tags:["Next.js","PostgreSQL / Prisma","RBAC","Dashboards"],sections:[["01 / Context","One operational view","Teams often need one place to see work, ownership, status and decisions instead of fragmented spreadsheets and messages."],["02 / System","Modules that connect","Clients, projects, tasks, tickets, documents and notifications can share a common identity and audit model."],["03 / Quality","Workflow confidence","Role-aware access, validation, status transitions and regression coverage keep operational changes predictable."],["04 / Outcome","Management visibility","The goal is not more screens. It is a clearer source of truth for day-to-day operations and decisions."]],flow:["Clients","Projects","Tasks","Tickets","Reports","Decisions"]},
 "qa-automation":{num:"03",type:"REPRESENTATIVE CAPABILITY",title:"QA Automation System",intro:"A representative quality-engineering capability for repeatable UI, API and database validation.",status:"Representative capability — not a client case study",tags:["Selenium","Java / TestNG","Postman","SQL"],sections:[["01 / Scope","Layered coverage","Test strategy can combine UI flows, API contracts and database checks so failures are easier to localize."],["02 / Framework","Reusable automation","Page objects, data-driven inputs, stable selectors and reporting help keep regression suites maintainable."],["03 / Pipeline","Fast feedback","Repeatable tests can run against controlled environments as part of a release workflow."],["04 / Outcome","Release confidence","Automation should remove repetitive checking while keeping exploratory and risk-based manual testing where it adds value."]],flow:["Plan","Design","Automate","Execute","Report","Retest"]},
 "ai-workflow":{num:"04",type:"REPRESENTATIVE CAPABILITY",title:"AI Workflow Automation",intro:"A controlled AI workflow concept connecting business input, intelligent processing, rules and human review.",status:"Representative capability — not a client case study",tags:["AI","APIs","Workflow automation","Human review"],sections:[["01 / Input","Capture the work","Collect structured or unstructured business input and normalize it before processing."],["02 / Intelligence","Apply the model","Use AI where it adds value, with clear boundaries around what the system may decide automatically."],["03 / Control","Keep humans in the loop","Escalate uncertain or sensitive outcomes for review rather than hiding uncertainty."],["04 / Outcome","Measure the workflow","Track throughput, exceptions and quality so automation can be improved responsibly."]],flow:["Input","Prepare","Reason","Validate","Approve","Act"]}
};
function SystemMap({p}){return <div className="caseSystem" data-tilt><div className="caseGrid"/><div className="caseCore">{p.num}<span>GANVESYS<br/>SYSTEM</span></div>{p.flow.map((x,i)=><div key={x} className={`caseNode caseN${i+1}`}><small>0{i+1}</small>{x}</div>)}<div className="caseRing cr1"/><div className="caseRing cr2"/></div>}
export default function ProjectDetail({params}){const p=projects[params.slug];if(!p)return <Shell><section className="splitHero"><div className="wrap"><div className="eyebrow">Project not found</div><h1>That project view does not exist.</h1><a className="btn primary" href="/projects">Back to projects</a></div></section></Shell>;return <Shell><main><section className="caseHero"><div className="wrap caseHeroGrid"><div><div className="eyebrow">{p.type} · {p.num}</div><h1>{p.title}</h1><p className="heroCopy">{p.intro}</p><div className="caseStatus">● {p.status}</div><div className="projectTags bigTags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="actions"><a className="btn primary" href="/contact">Discuss a similar system ↗</a><a className="btn" href="/projects">All projects</a></div></div><SystemMap p={p}/></div></section><section><div className="wrap"><div className="caseSections">{p.sections.map((s,i)=><article className="caseSection" key={s[1]} data-reveal><div className="caseSectionNum">{s[0]}</div><div><h2>{s[1]}</h2><p>{s[2]}</p></div></article>)}</div></div></section><section className="darkSection"><div className="wrap darkInner"><div className="sectionTop"><div><div className="eyebrow">System flow</div><h2>Make the workflow visible.</h2></div><p>Each project can be decomposed into clear stages so ownership, quality and decision points are easier to manage.</p></div><div className="caseFlow">{p.flow.map((x,i)=><div key={x} className="caseFlowStep"><span>0{i+1}</span><b>{x}</b>{i<p.flow.length-1&&<i>→</i>}</div>)}</div></div></section><section className="cta"><div className="wrap ctaBox"><div><div className="eyebrow">Build something similar</div><h2>Bring us the workflow.</h2><p className="muted">We’ll help translate the requirement into architecture, delivery and QA.</p></div><a className="btn primary" href="/contact">Start a conversation ↗</a></div></section></main></Shell>}
