import {Shell} from "../components";

const projects=[
 {slug:"smartgate",num:"01",type:"INTERNAL PRODUCT SIMULATION",title:"SMARTGATE",subtitle:"Visitor management, approvals and secure gate workflows.",desc:"A professional internal product simulation created to demonstrate how GANVESYS approaches requirements, product engineering, QA and release readiness around a real operational workflow.",tags:["Product Engineering","PostgreSQL","Node / TypeScript","QA Engineering"],accent:"blue",status:"SIMULATION / PRODUCT EXERCISE"},
 {slug:"enterprise-operations",num:"02",type:"REPRESENTATIVE CAPABILITY",title:"Enterprise Operations Platform",subtitle:"Connected workflows for teams, records and business operations.",desc:"A representative platform concept showing how dashboards, role-aware workflows, data models and reporting can be brought together into one operating system.",tags:["Web Platform","RBAC","Workflows","Reporting"],accent:"violet",status:"REPRESENTATIVE CAPABILITY"},
 {slug:"qa-automation",num:"03",type:"REPRESENTATIVE CAPABILITY",title:"QA Automation System",subtitle:"Repeatable coverage across UI, API and data layers.",desc:"A representative quality-engineering capability covering functional testing, API validation, browser automation and data-driven regression workflows.",tags:["Selenium","TestNG","Postman","SQL"],accent:"cyan",status:"REPRESENTATIVE CAPABILITY"},
 {slug:"ai-workflow",num:"04",type:"REPRESENTATIVE CAPABILITY",title:"AI Workflow Automation",subtitle:"Human-guided automation for repetitive business work.",desc:"A representative AI workflow concept that connects input, intelligent processing, business rules and human review into a controlled operational flow.",tags:["AI","Automation","Human-in-loop","APIs"],accent:"purple",status:"REPRESENTATIVE CAPABILITY"}
];

function ProjectCard({p}){return <a className={`projectCard ${p.accent}`} href={`/projects/${p.slug}`} data-reveal><div className="projectCardTop"><span>{p.num}</span><span>{p.status}</span></div><div className="projectMiniVisual"><div className="miniCore">GV</div><i/><i/><i/><i/></div><div className="projectType">{p.type}</div><h3>{p.title}</h3><p>{p.desc}</p><div className="projectTags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="projectArrow">Open project view <b>↗</b></div></a>}

export default function Projects(){return <Shell><main>
 <section className="splitHero projectsHero"><div className="wrap projectsHeroGrid"><div><div className="eyebrow">Projects / engineering portfolio</div><h1>Proof of how we <span className="gradientText">think and build.</span></h1><p className="heroCopy">Explore internal product simulations and representative engineering capabilities. We separate demonstrated work from client claims — clearly.</p><div className="actions"><a className="btn primary" href="/projects/smartgate">Explore SMARTGATE ↗</a><a className="btn" href="/contact">Discuss a requirement</a></div></div><div className="portfolioCanvas" data-tilt data-reveal><div className="portfolioGrid"/><div className="portfolioOrb">GV<span>PROJECT<br/>SYSTEM</span></div><div className="portfolioLine pl1"/><div className="portfolioLine pl2"/><div className="portfolioLine pl3"/><div className="portfolioLabel lA">PRODUCT</div><div className="portfolioLabel lB">QUALITY</div><div className="portfolioLabel lC">AUTOMATION</div><div className="portfolioLabel lD">DATA</div></div></div></section>
 <section><div className="wrap"><div className="sectionTop" data-reveal><div><div className="eyebrow">Selected work</div><h2>Different problems. One disciplined engineering approach.</h2></div><p>These examples are intentionally labeled. SMARTGATE is an internal professional simulation; the other entries are representative capability concepts, not fabricated client case studies.</p></div><div className="projectGrid">{projects.map(p=><ProjectCard key={p.slug} p={p}/>)}</div></div></section>
 <section className="darkSection"><div className="wrap darkInner"><div className="sectionTop" data-reveal><div><div className="eyebrow">Project lifecycle</div><h2>Every project becomes a system of decisions.</h2></div><p>Requirements, architecture, implementation, testing and release are connected. The visual below shows the checkpoints we keep visible.</p></div><div className="projectTimeline" data-reveal>{["Discover","Architect","Build","Validate","Release","Improve"].map((x,i)=><div className="timelineItem" key={x}><span>0{i+1}</span><div className="timelineDot"/><h3>{x}</h3><p>{["Define the outcome and constraints.","Choose the system shape and ownership.","Deliver the smallest useful increment.","Test risk, behavior and integrations.","Move through a controlled release path.","Use feedback to improve the system."][i]}</p></div>)}</div></div></section>
 <section className="projectPrinciples"><div className="wrap"><div className="sectionTop" data-reveal><div><div className="eyebrow">What we show</div><h2>Real engineering detail, without invented stories.</h2></div></div><div className="principleGrid"><div data-reveal><b>01</b><h3>Context</h3><p>What problem the system is designed to solve and who interacts with it.</p></div><div data-reveal><b>02</b><h3>Architecture</h3><p>How product, API, data, security and quality concerns connect.</p></div><div data-reveal><b>03</b><h3>Quality</h3><p>What is validated, automated and monitored before release.</p></div><div data-reveal><b>04</b><h3>Outcome</h3><p>What the system enables — without making unsupported business claims.</p></div></div></div></section>
 <section className="cta"><div className="wrap ctaBox" data-reveal><div><div className="eyebrow">Have a workflow to improve?</div><h2>Let's turn it into a system.</h2><p className="muted">Bring the requirement. We’ll map the product, engineering and quality path.</p></div><a className="btn primary" href="/contact">Start a conversation ↗</a></div></section>
 </main></Shell>}
