import {Shell,RevealCard} from "./components";

function ProductVisual(){return <div className="heroSystemVisual" data-tilt aria-label="Animated GANVESYS engineering system visual">
  <div className="systemGlow gA"/><div className="systemGlow gB"/>
  <div className="systemRing sr1"/><div className="systemRing sr2"/><div className="systemRing sr3"/>
  <div className="systemCore"><span className="corePulse"/><b>GV</b><small>ENGINE</small></div>
  <div className="systemNode sn1"><i/>AI <b>Automation</b></div>
  <div className="systemNode sn2"><i/>QA <b>Quality</b></div>
  <div className="systemNode sn3"><i/>CLOUD <b>Scale</b></div>
  <div className="systemNode sn4"><i/>DATA <b>Insight</b></div>
  <div className="systemNode sn5"><i/>SECURITY <b>Protect</b></div>
  <div className="systemNode sn6"><i/>PRODUCT <b>Build</b></div>
  <div className="systemBeam beam1"/><div className="systemBeam beam2"/><div className="systemBeam beam3"/>
  <div className="systemStatus ss1"><span className="statusDot"/> SYSTEMS CONNECTED</div>
  <div className="systemStatus ss2">BUILD <b>→</b> TEST <b>→</b> SCALE</div>
 </div>}

export default function Home(){return <Shell><main>
 <section className="hero heroV51"><div className="wrap heroGrid"><div data-reveal>
  <div className="eyebrow">GANVESYS TECHNOLOGIES · ENGINEERING STUDIO</div>
  <h1>We build <span className="gradientText">systems that move business forward.</span></h1>
  <p className="heroCopy">Software engineering, AI automation, quality engineering and cloud systems — designed as one connected technology capability.</p>
  <div className="actions"><a className="btn primary" href="/contact">Start a project ↗</a><a className="btn" href="/services">Explore capabilities</a></div>
  <div className="heroMeta"><div><strong>01</strong>Build</div><div><strong>02</strong>Automate</div><div><strong>03</strong>Scale</div></div>
 </div><ProductVisual/></div></section>
 <div className="trustBar"><div className="wrap trustInner"><span className="trustLabel">Engineering across</span><div className="trustItems"><span>PRODUCT</span><span>AI</span><span>QUALITY</span><span>CLOUD</span><span>DATA</span><span>SECURITY</span></div></div></div>
 <div className="ticker"><div className="tickerTrack">{["SOFTWARE ENGINEERING","AI & AUTOMATION","QA ENGINEERING","CLOUD & DEVOPS","CYBER SECURITY","DATA SYSTEMS","SOFTWARE ENGINEERING","AI & AUTOMATION","QA ENGINEERING","CLOUD & DEVOPS","CYBER SECURITY","DATA SYSTEMS"].map((x,i)=><span key={i}>{x}</span>)}</div></div>
 <section><div className="wrap"><div className="sectionTop" data-reveal><div><div className="eyebrow">What we engineer</div><h2>Technology that feels simple on the surface.</h2></div><p>Behind a clean experience is disciplined engineering: architecture, automation, testing, data and infrastructure working together.</p></div>
  <div className="serviceGrid">{[
   ["01 · Build","Software Engineering","Modern web platforms, APIs and business systems engineered for reliability and growth.","⌘"],["02 · Intelligence","AI & Automation","Practical AI workflows and automation that reduce repetitive work and improve decisions.","✦"],["03 · Quality","QA & Test Automation","Manual and automated quality engineering across web, API and critical business workflows.","✓"],["04 · Infrastructure","Cloud & DevOps","Deployment foundations, environments and operational practices designed for scale.","☁"],["05 · Protection","Cyber Security","Security-minded engineering, access controls and safer application foundations.","◈"],["06 · Data","Data & Digital","Connected data flows and digital experiences that turn operations into useful insight.","◌"]
  ].map((x,i)=><div key={x[1]} data-reveal style={{transitionDelay:`${i*70}ms`}}><RevealCard tag={x[0]} title={x[1]} text={x[2]} icon={x[3]}/></div>)}</div>
 </div></section>
 <section className="visualBand"><div className="wrap"><div className="sectionTop" data-reveal><div><div className="eyebrow">Inside the system</div><h2>Not a brochure. A view into how we think.</h2></div><p>Product, automation, quality and infrastructure are connected by design. The visual below represents that delivery model.</p></div>
  <div className="visualStage" data-reveal data-tilt><div className="stageGrid"/><div className="stageTitle"><div className="eyebrow">GANVESYS ENGINE</div><h3>Connected delivery.</h3><p>One operating model for building, validating and scaling digital systems.</p></div><div className="stageStats"><div className="stageStat"><small>DELIVERY</small><b>DISCOVER → BUILD</b></div><div className="stageStat"><small>QUALITY</small><b>TEST → HARDEN</b></div><div className="stageStat"><small>OPERATIONS</small><b>DEPLOY → SCALE</b></div></div><div className="orbit o1"><i className="orbitNode on1"/><i className="orbitNode on3"/></div><div className="orbit o2"><i className="orbitNode on2"/><i className="orbitNode on4"/></div><div className="orbit o3"/><div className="orbitCore">GANVESYS<br/>ENGINE</div></div>
 </div></section>
 <section className="portfolioPreview"><div className="wrap"><div className="sectionTop" data-reveal><div><div className="eyebrow">Selected projects</div><h2>See the engineering behind the experience.</h2></div><p>Explore an internal product simulation and representative capability systems — presented honestly, with architecture and workflow detail.</p></div><div className="projectPreviewGrid"><a className="projectPreview main" href="/projects/smartgate" data-reveal><div className="previewVisual"><div className="previewCore">SMART<br/><span>GATE</span></div><div className="previewOrbit po1"/><div className="previewOrbit po2"/></div><div className="previewMeta"><span>01 · INTERNAL PRODUCT SIMULATION</span><b>SMARTGATE ↗</b></div><p>Visitor management, approvals, gate workflows and QA-ready system design.</p></a><div className="previewStack"><a href="/projects/enterprise-operations" className="projectPreview compact" data-reveal><div className="compactVisual"><i/><i/><i/></div><div><span>02 · REPRESENTATIVE</span><b>Enterprise Operations ↗</b><p>Connected workflows and management visibility.</p></div></a><a href="/projects/qa-automation" className="projectPreview compact" data-reveal><div className="compactVisual cyan"><i/><i/><i/></div><div><span>03 · REPRESENTATIVE</span><b>QA Automation ↗</b><p>UI, API and data-layer quality engineering.</p></div></a></div></div><div className="actions portfolioAction"><a className="btn" href="/projects">View all projects ↗</a></div></div></section>
<section className="darkSection"><div className="wrap darkInner"><div className="architecture"><div data-reveal><div className="eyebrow">Engineering architecture</div><h2>One system. Multiple capabilities. Built to connect.</h2><p className="muted">GANVESYS brings product engineering, AI, quality and infrastructure into a single delivery mindset — so teams can move from idea to dependable system without unnecessary handoffs.</p><div className="actions"><a className="btn blue" href="/solutions">See our approach ↗</a></div></div>
  <div className="architectureVisual" data-reveal data-tilt><div className="archGrid"/><div className="archCore">GANVESYS<br/>ENGINE</div><div className="archNode n1">AI / AUTOMATION</div><div className="archNode n2">PRODUCT</div><div className="archNode n3">QUALITY</div><div className="archNode n4">CLOUD</div></div></div>
  <div className="capGrid" style={{marginTop:35}} data-reveal><div className="cap"><strong>01</strong><span>Discover & define</span></div><div className="cap"><strong>02</strong><span>Design & engineer</span></div><div className="cap"><strong>03</strong><span>Test & harden</span></div><div className="cap"><strong>04</strong><span>Deploy & improve</span></div></div>
 </div></section>
 <section><div className="wrap"><div className="sectionTop" data-reveal><div><div className="eyebrow">Engineering mindset</div><h2>Built for the work behind the interface.</h2></div><p>We care about the details users never see: clean APIs, resilient workflows, testability, observability and secure foundations.</p></div>
  <div className="storyGrid"><div className="storyCard" data-reveal><div className="eyebrow">01 / Product</div><h3>Make complexity disappear.</h3><p>Great technology turns complicated workflows into clear experiences. We start with the operating problem, not the framework.</p><div className="storyGlow"/></div><div className="storyCard dark" data-reveal style={{transitionDelay:'.08s'}}><div className="eyebrow">02 / Quality</div><h3>Confidence is engineered.</h3><p>Testing, automation and security are part of the build — not a final gate after everything else is done.</p><div className="storyGlow"/></div></div>
 </div></section>
 <section style={{paddingTop:20}}><div className="wrap"><div className="sectionTop" data-reveal><div><div className="eyebrow">How we work</div><h2>From problem to production.</h2></div></div><div className="process">{["Discover","Design","Engineer","Test","Deploy","Scale"].map((x,i)=><div className="step" key={x} data-reveal style={{transitionDelay:`${i*50}ms`}}><div className="stepNo">0{i+1}</div><h3>{x}</h3><p>{["Clarify the outcome, users and constraints.","Turn requirements into a clear system.","Build the product and its foundations.","Validate behavior, reliability and security.","Release with a controlled delivery path.","Measure, improve and extend the system."][i]}</p></div>)}</div></div></section>
 <section className="cta"><div className="wrap ctaBox" data-reveal><div><div className="eyebrow">Have a system to build?</div><h2>Let's engineer it.</h2><p className="muted">Tell us what you are trying to solve. We’ll turn the conversation into a practical engineering path.</p></div><a className="btn primary" href="/contact">Start a conversation ↗</a></div></section>
 </main></Shell>}
