import {Shell} from "../../components";

const data={
 "software-engineering":{eyebrow:"01 · Build",title:"Software Engineering",intro:"Digital products and business systems engineered around clear workflows, maintainable architecture and dependable delivery.",accent:"BUILD",outcome:"Turn a requirement into a usable, testable system.",focus:["Web applications and portals","Backend APIs and business services","Internal operations platforms","Authentication and role-aware workflows"],steps:["Understand the workflow","Design the architecture","Build the critical path","Validate and improve"],visual:["FRONTEND","API","DATA","AUTH"]},
 "ai-automation":{eyebrow:"02 · Intelligence",title:"AI & Automation",intro:"Practical AI and workflow automation for teams that want to remove repetitive work without losing control.",accent:"AI",outcome:"Move repetitive decisions and actions into reliable workflows.",focus:["AI-assisted business workflows","Document and text processing","Task automation","Human-in-the-loop experiences"],steps:["Map repetitive work","Identify safe automation","Connect systems and data","Measure the outcome"],visual:["INPUT","MODEL","WORKFLOW","HUMAN"]},
 "qa-test-automation":{eyebrow:"03 · Quality",title:"QA & Test Automation",intro:"Quality engineering that combines thoughtful manual testing with repeatable automation across UI, API and data layers.",accent:"QA",outcome:"Increase release confidence without slowing delivery.",focus:["Functional and regression testing","API and integration testing","Selenium / browser automation","Data-driven test frameworks"],steps:["Model the risk","Design coverage","Automate repeatable paths","Report and retest"],visual:["TESTS","UI","API","DB"]},
 "cloud-devops":{eyebrow:"04 · Infrastructure",title:"Cloud & DevOps",intro:"Delivery foundations that make environments, releases and operations easier to understand and repeat.",accent:"CLOUD",outcome:"Create a safer path from code to a running system.",focus:["Environment strategy","CI/CD direction","Deployment workflows","Operational readiness"],steps:["Map environments","Standardize delivery","Automate repeatable steps","Observe and improve"],visual:["CODE","BUILD","DEPLOY","RUN"]},
 "cyber-security":{eyebrow:"05 · Protection",title:"Cyber Security",intro:"Security-minded product engineering focused on identity, access, safer defaults and disciplined operational foundations.",accent:"SECURE",outcome:"Reduce avoidable exposure while keeping the product usable.",focus:["Authentication and sessions","Role-based access","Secure application defaults","Security-aware QA"],steps:["Identify trust boundaries","Protect identity","Validate access","Monitor and improve"],visual:["IDENTITY","ACCESS","DATA","AUDIT"]},
 "data-digital-transformation":{eyebrow:"06 · Data",title:"Data & Digital Transformation",intro:"Connected data flows and modern digital workflows that turn fragmented operations into clearer systems and useful information.",accent:"DATA",outcome:"Make operational information easier to capture, connect and use.",focus:["Operational data models","Dashboards and reporting","Workflow modernization","System integration"],steps:["Map information flow","Model the source of truth","Connect the workflow","Turn data into action"],visual:["CAPTURE","CONNECT","ANALYZE","ACT"]}
};

function SystemVisual({item}){return <div className="detailVisual" data-tilt><div className="detailGrid"/><div className="detailOrb">{item.accent}</div><div className="detailWire dw1"/><div className="detailWire dw2"/><div className="detailWire dw3"/>{item.visual.map((x,i)=><div className={`detailNode dn${i+1}`} key={x}><span>0{i+1}</span>{x}</div>)}<div className="detailPulse"/></div>}

export default function ServiceDetail({params}){const item=data[params.slug];if(!item)return <Shell><section className="splitHero"><div className="wrap"><div className="eyebrow">Capability not found</div><h1>That page does not exist.</h1><a className="btn primary" href="/services">Back to services</a></div></section></Shell>;return <Shell>
 <section className="detailHero"><div className="wrap detailHeroGrid"><div><div className="eyebrow">GANVESYS / {item.eyebrow}</div><h1>{item.title}</h1><p className="heroCopy">{item.intro}</p><div className="actions"><a className="btn primary" href="/contact">Discuss this capability ↗</a><a className="btn" href="/services">All services</a></div></div><SystemVisual item={item}/></div></section>
 <section><div className="wrap"><div className="sectionTop"><div><div className="eyebrow">Where it helps</div><h2>{item.outcome}</h2></div><p>We keep the scope grounded in the workflow and technical constraints rather than forcing a one-size-fits-all stack.</p></div><div className="featureGrid">{item.focus.map((x,i)=><div className="feature detailFeature" key={x}><span className="detailNum">0{i+1}</span><h3>{x}</h3><p>Designed as a practical capability within a larger delivery system.</p></div>)}</div></div></section>
 <section className="darkSection"><div className="wrap darkInner"><div className="sectionTop"><div><div className="eyebrow">Delivery path</div><h2>How we take this from idea to working capability.</h2></div><p>Clear stages make ownership visible and create checkpoints for feedback, quality and technical decisions.</p></div><div className="process detailProcess">{item.steps.map((x,i)=><div className="step" key={x}><div className="stepNo">0{i+1}</div><h3>{x}</h3><p>Define the next smallest useful increment and validate it before expanding the scope.</p></div>)}</div></div></section>
 <section className="cta"><div className="wrap ctaBox"><div><div className="eyebrow">Next step</div><h2>Have a requirement for {item.title}?</h2><p className="muted">Tell us what you need. We can shape the capability around your workflow.</p></div><a className="btn primary" href="/contact">Start a conversation ↗</a></div></section>
 </Shell>}
